//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Food_Recipes_ASP.NET_WebForm
{


    public partial class Services_Detail
    {

        /// <summary>
        /// Comments control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Food_Recipes_ASP.NET_WebForm.userControls.Comments Comments;

        /// <summary>
        /// PostComments control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Food_Recipes_ASP.NET_WebForm.userControls.PostComments PostComments;

        /// <summary>
        /// PostRecents control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Food_Recipes_ASP.NET_WebForm.PostRecents PostRecents;
    }
}
